name: smartrider
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #firebase dependencies
  firebase_core: ^0.5.2
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3

  #map dependencies
  google_maps_flutter: ^1.0.6
  polyline: ^1.0.2
  geolocator: ^6.1.4
  geocoder: ^0.2.1
  google_maps_webservice: ^0.0.16
  http: ^0.12.0+4
  rxdart: ^0.23.1
  fluster: ^1.1.2
  protobuf: ^1.0.1

  #saferide dependencies
  hypertrack_views_flutter: ^0.1.0

  #notication dependencies
  flutter_local_notifications: ^1.4.4+2

  #ui dependencies
  sliding_up_panel: ^1.0.2
  scrollable_positioned_list: ^0.1.8
  google_fonts: ^0.3.9
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  flutter_svg: ^0.19.1
  modal_progress_hud: ^0.1.3
  table_sticky_headers: ^1.2.0
  showcaseview: 
  feature_discovery: ^0.13.0+2

  #state management
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/app_icons/logo_v1.png
    - assets/app_icons/logo_v2.png
# jsons
    - assets/map_styles/light.json
    - assets/map_styles/aubergine.json

# map icons
    - assets/bus_icons/
    - assets/shuttle_icons/

#notification
    - assets/Notification_Icons/app_logo.png

#onboarding 
    - assets/onboarding_images/rpi_stock_photo.png
    - assets/onboarding_images/onboarding_page2_1.png
    - assets/onboarding_images/onboarding_page2_2.png
    - assets/onboarding_images/onboarding_page3_1.png
    - assets/onboarding_images/onboarding_page3_2.png
    - assets/onboarding_images/onboarding_page4_1.png
    - assets/onboarding_images/interactive_map.png
    - assets/onboarding_images/comprehensive_scheduling.png
    - assets/onboarding_images/customizable_view.png
    - assets/onboarding_images/request_transportation.png
  fonts:
    - family: SR_Icons
      fonts:
        - asset: fonts/icons.ttf
