name: smartrider
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #firebase dependencies
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.0+1s
  cloud_firestore: ^0.12.9+5

  #map dependencies
  google_maps_flutter: ^0.5.24+1
  polyline: ^1.0.2
  geolocator: ^6.0.0+4
  google_maps_webservice: ^0.0.16
  http: ^0.12.0+4
  rxdart: ^0.23.1
  fluster: ^1.1.2

  protobuf: ^1.0.1


  #ui dependencies
  sliding_up_panel: ^1.0.1
  scrollable_positioned_list: ^0.1.2
  google_fonts: ^0.3.9
  cupertino_icons: ^0.1.2
  day_night_switch: ^0.0.2+1
  intl: ^0.16.1
  day_night_switcher: ^0.1.1
  flutter_dash: ^0.0.1

  dio: ^3.0.9
  flutter_archive: ^1.0.2

  #state management
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  provider: ^4.1.3
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    # jsons
    - assets/map_styles/light.json
    - assets/map_styles/aubergine.json

    - assets/bus_jsons/shapes.geojson
    # map markers
    - assets/stop_markers/marker_bus.png
    - assets/stop_markers/marker_shuttle.png
    - assets/bus_markers/bus_red.png
    - assets/bus_markers/bus_blue.png
    - assets/bus_markers/bus_yellow.png
    - assets/bus_markers/bus_orange.png
    - assets/bus_markers/bus_white.png

  fonts:
    - family: SR_Icons
      fonts:
        - asset: fonts/icons.ttf
