name: smartrider
description: A new Flutter project.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #local packages
  shared:
    path: ../shared/

  cloud_firestore: ^2.5.4
  cloud_functions: ^3.0.5
  firebase_messaging: ^11.1.0
  device_preview: ^1.0.0
  equatable: ^2.0.2
  # firebase_analytics: ^8.1.1
  firebase_auth: ^3.1.4
  firebase_core: ^1.7.0
  firebase_dynamic_links: ^4.0.5
  flex_color_scheme: ^4.2.0
  fluster: ^1.2.0
  flutter_bloc: ^7.0.1
  flutter_inappwebview: ^5.3.2
  flutter_keyboard_visibility: ^5.0.2
  flutter_local_notifications: ^9.0.0
  flutter_svg: ^0.22.0
  flutter_typeahead: ^3.1.3
  geolocator: ^8.1.1
  google_maps_flutter: ^2.0.11
  google_maps_flutter_web: ^0.3.0+2
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.3
  intl: ^0.17.0
  ntp: ^2.0.0
  oauth2_client: ^2.2.0
  protobuf: ^2.0.0
  responsive_framework: ^0.1.4
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  shared_preferences: ^2.0.6
  showcaseview: ^1.0.0
  sizer: ^2.0.13
  sms_autofill: ^2.2.0
  table_sticky_headers: ^2.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  very_good_analysis: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    # jsons
    - assets/map_styles/light.json
    - assets/map_styles/aubergine.json

    # map icons
    - assets/map_icons/

    #onboarding
    - assets/onboarding_images/
  fonts:
    - family: SR_Icons
      fonts:
        - asset: fonts/icons.ttf
