/// Flutter icons SmartRider
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SR_Icons
///      fonts:
///       - asset: fonts/SmartRider.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SmartriderIcons {
  SmartriderIcons._();

  static const _kFontFam = 'SR_Icons';

  static const IconData Settings =
      const IconData(0xe800, fontFamily: _kFontFam);
}
